### ISSUE TITLE
Easyblock for Quantum Espresso with ELPA

### ISSUE THREAD

**Issue by hfp** [easybuilders/easybuild-easyblocks#1061]
I wonder if the Easyblock for QE can incorporate ELPA, which is known to be beneficial in terms of performance?

Since QE 6.0, the newer ELPA libraries can be [taken](http://elpa.rzg.mpg.de/elpa-tar-archive). QE calls them (wisely) ELPA 2015 and ELPA 2016 (and perhaps needs to introduce ELPA'17 if MPG sticks with changing it again [2016.11.001.pre]). I believe one should look at this option anyways since QE6 does not include ELPA anymore (it did so prior to 6.0; however it was an outdated version without support for AVX2 , etc.).

One may have a look at https://github.com/hfp/xconfigure#xconfigure, which is also something like an Easyblock, but less sophisticated (and only focused on Intel tools). With the latter, you can also patch older QE 5.x to make use of a recent ELPA library.

**Comment by boegel** [comment]
@hfp Thanks for the suggestion, it definitely sounds worthwhile to look into making the QE easyblock aware of ELPA!

Are you interested in helping out with this, since you clearly have extensive experience with this?

Maybe contributing back to what you currently have supported in `xconfigure` makes sense?

Most of the software supported in EasyBuild has been tested with the Intel compilers & tools, since we (HPC-UGent) try to use a toolchain that consists of Intel compilers + MPI + MKL exclusively for software installations.

**Comment by wpoely86** [comment]
I once started working on ELPA but hit some configure error. I haven't found time to continue: hpcugent/easybuild-easyconfigs#3891

**Comment by akesandgren** [comment]
This was fixed in https://github.com/easybuilders/easybuild-easyblocks/pull/1312
