### ISSUE TITLE
cmd_prefix in generic configuremake.py is not being set

### ISSUE THREAD

**Issue by jpc2350** [easybuilders/easybuild-easyblocks#1279]
Hi @boegel, I wonder if you could give me an understanding of the cmd_prefix variable in generic configuremake.py.

I've got a piece of software that requires to run the configure command from a different directory, but there is no way (I can see, please correct if I'm wrong) to get the current build_dir.

I see that we can use configure_cmd_prefix which allows us to define a specific directory, but I'd like to have it dynamically set rather than statically defined. I also see within this, that cmd_prefix is set to ' ' but this is not set to the build_dir, and seemingly doesn't get used. 
Should cmd_prefix be dynamically set to the build_dir of the tool building at the time? and if not, how can we get this 'dynamic' directory from easybuild?

**Comment by boegel** [comment]
@jpc2350 `cmd_prefix` is rarely used indeed, it is intended for allowing you to run a configure command that is located elsewhere though.

To get the current build directory, you can use the template `%(builddir)s`.

Something like this may be what you're after:

```prefix
cmd_prefix = '%(builddirs)/some/subdir/'
```

Which should end up calling configure like `%(builddirs)/some/subdir/./configure` (the `/./` looks weird but is harmless, it'll occur because the `./` in `./configure` is hardcoded in `ConfigureMake`).

If this answers your questions, please let us know & close this issue.

**Comment by jpc2350** [comment]
Hi @boegel,
sorry for the late response - i've only just managed to get back to this issue.

I've created an easyblock with the following:

```
def configure_step(self):
        """Configure <SOFTWARE> build, set to update cmd_prefix to be the builddir."""

        self.cfg.update('configure_cmd_prefix', '%(builddir)s/')

        super(<CLASSNAME>, self).configure_step()
```

But I get the following response when trying to build:
ERROR EasyBuild crashed with an error (at ?:124 in __init__): cmd "cd ../ &&  <some/dir>easybuild/build/<SOFTWARE>/<VERSION>/dummy- ./configure --prefix=<install/directory> " exited with exitcode 126 and output:
/bin/bash: <some/dir>/easybuild/build/<SOFTWARE>/<VERSION>/dummy-: Is a directory
 (at easybuild/tools/run.py:469 in parse_cmd_output)

It looks like there is a space between the builddir and the ./configure command, i wonder if there is a way to stop this happening?

**Comment by jpc2350** [comment]
Hi @boegel,

So I've done a little more in-depth work on this, and although I'm still getting the error (I'm not sure why the formatting of the cmd is not working) I think i'm getting somewhere. My settings are:
`preconfigopts: mkdir ../build && cd ../build &&`
`self.cfg.update('configure_cmd_prefix', '%s/' % self.builddir)` - which should actually be `startdir`
which then forms the following command to be running at configure_step.
```
"mkdir ../build && cd ../build &&  /home/jcullum/.local/easybuild/build/manta/1.1.1/dummy-/ ./configure --prefix=/tools/ebpoc/apps/manta/1.1.1
```
I still don't get where the whitespace is coming in, including between preconfigopts and cmd_prefix

**Comment by boegel** [comment]
@jpc2350 To access `startdir`, you'll need to use `self.cfg['start_dir']` rather than `self.startdir`. I understand the confusion here, we should probably clean that up since `self.startdir` (or `self.start_dir`) is definitely cleaner.

W.r.t. the extra trailing space: that's the default behaviour of `self.cfg.update`, see https://github.com/easybuilders/easybuild-framework/blob/master/easybuild/framework/easyconfig/easyconfig.py#L384.

Since you want to override the value rather than append to it (which is what `self.cfg.update` does), you can use this though?

```python
self.cfg['configure_cmd_prefix'] = self.cfg['start_dir']

**Comment by jpc2350** [comment]
Hi @boegel,

Great thanks, that worked.

Certainly, if it's accessed like `self.builddir` then it would be cleaner and friendlier. Fortunately, this is the only software that I have come across so far that needs to be built outside of the source dir

**Comment by boegel** [comment]
Support for `self.start_dir` is implemented in https://github.com/easybuilders/easybuild-framework/pull/2339, so I'll close this issue.
