### ISSUE TITLE
VMD has lost the Extensions->Analysis option in the GUI somewhere between EB 3.5.2 and 3.9.0.

### ISSUE THREAD

**Issue by JackPerdue** [easybuilders/easybuild-easyblocks#1755]
We have this version of of VMD installed:

$ head VMD-1.9.3-foss-2017b-Python-2.7.14.eb
# Built with EasyBuild version 3.5.2 on 2018-03-04_09-19-36

In the vmd GUI, there is an Extensions->Analysis option available that apparently our users would like to use.  It works well for that build.... all later builds seem to be lacking it.

Building the latest version (3.9.1) of that easyconfig (its changed) with the latest EasyBuild (3.9.1), there is no Extensions->Analysis option.  

I've tried to track down the change but am not seeing it.  Any ideas?

**Comment by boegel** [comment]
@JackPerdue Sorry for picking up on this rather late...

What happens if you go back and use EasyBuild v3.5.2 to install `VMD` (in a temporary directory)?
Do you obtain an installation that has that specific feature?

Maybe it was enabled back then because of some OS package being installed that is required for that feature?

**Comment by seb45tian** [comment]
I think I (maybe) came across the same problem. Creating a new EasyConfig of VMD-1.9.3 for the 2019a toolchain I noticed that the _Extensions_ menu is completely empty. After some googlefoo this is supposed to happen when you forget to specify **TK** in the configure command. However TK is specified as a dependency and therefore should be added to the _configopts_. Unfortunately this is prevented by the addition of `allow_duplicate=False` (added by this commit https://github.com/easybuilders/easybuild-easyblocks/commit/dd270b67bf5cb0a91c130d0c033750556b072327 ) because FLTK is also a dependency and EB treats TK as a duplicate. And indeed setting `allow_duplicate=True` solves this for me. 

I don't know the correct way to fix this as the commit preventing the duplicates is apparently fixing a rebuild  issue. Any thoughts?

**Comment by akesandgren** [comment]
Real problem identified, discussing solution...

**Comment by akesandgren** [comment]
Solved by https://github.com/easybuilders/easybuild-framework/pull/3170
