### ISSUE TITLE
root.py sets wrong PYTHON_INCLUDE_DIR and PYTHON_LIBRARY when using Python3

### ISSUE THREAD

**Issue by JackPerdue** [easybuilders/easybuild-easyblocks#2009]
So while trying to built ROOT with Python3 (customer request), we see this during the configure_step:

-DPYTHON_INCLUDE_DIR=/sw/eb/sw/Python/3.6.6-foss-2018b/include/python3.6
-DPYTHON_LIBRARY=/sw/eb/sw/Python/3.6.6-foss-2018b/lib/libpython3.6.so

In both cases, the trailing python3.6 should be python3.6m.  This is not "easy" to work around because the easyblock setting overrides any configopts setttings.  So it requires a lot of work after the configure step to tweak the right files to change 3.6 to 3.6m.

I call this a bug.  I find it annoying.  Please fix it.

**Comment by kelseymh** [comment]
As a followup (I'm the customer), it appears that the wrong setting is in [root.py line 84](https://github.com/easybuilders/easybuild-easyblocks/blob/af41c4774c7249511c50e8a53b3c04326d6d2dc6/easybuild/easyblocks/r/root.py#L84), where an example of a "right" solution is in [blender.py line 89](https://github.com/easybuilders/easybuild-easyblocks/blob/af41c4774c7249511c50e8a53b3c04326d6d2dc6/easybuild/easyblocks/b/blender.py#L89).

It seems as though (within th limitations of GitHub's search capability) that there are many instances of the python-setting code block throughout easyblocks.

**Comment by kelseymh** [comment]
I have tested a fix for this issue, by copying the relevant individual lines from blender.py and adapting them into root.py.  I suspect that a proper fix, from the developers, would probably involve pusing the "find_glob_pattern" up to a base class like CMakeMake, or even higher, and maybe dealing with the set of python CMake options in a more encapsulated way, rather than in each individual easyblock.

Anyway, I've attached a diff for root.py showing what I've done.  If the developers would like me to do a pull request, I can, or I can leave it to them to do it right.
[root.py-diff.txt](https://github.com/easybuilders/easybuild-easyblocks/files/4424001/root.py-diff.txt)

**Comment by JackPerdue** [comment]
My customer's Python kung fu is better than mine. :)  Anyway, submitted the easyconfig (also written by the customer) as a PR for reference.

**Comment by kelseymh** [comment]
Sigh.  I forked easybuilders and submitted the pull request.  I wasn't able to attach to this issue (probably because I'm not the one who created the issue), so the pull request was assigned issue #2010, but I had already given the branch name "2009_...".  Apologies to the Git maintainers.

**Comment by lexming** [comment]
Fixed with #2010. Thanks @JackPerdue and @kelseymh for reporting this.
