### ISSUE TITLE
Github command-line API for pull requests is being deprecated

### ISSUE THREAD

**Issue by kelseymh** [easybuilders/easybuild-easyblocks#2011]
Today I did my first pull request for easyblocks (see issue #2010), and I tried using the command-line (curl) interface described in [CONTRIBUTING.rst](https://github.com/easybuilders/easybuild-easyblocks/blob/develop/CONTRIBUTING.md#issue-pull-request-for-existing-ticket-from-command-line).  I got an e-mail back from GitHub warning me,

> Basic authentication using a password to the API is deprecated and will soon no longer work. Visit https://developer.github.com/changes/2020-02-14-deprecating-password-auth/ for more information around suggested workarounds and removal dates.

**Comment by ocaisa** [comment]
This is related to https://developer.github.com/v3/auth/#via-username-and-password and doesn't come from anything to do with EasyBuild, if you [register an ssh key with GitHub](https://help.github.com/en/github/authenticating-to-github/adding-a-new-ssh-key-to-your-github-account) this warning will go away.  Part of the [EasyBuild GitHub integration requirements](https://easybuild.readthedocs.io/en/latest/Integration_with_GitHub.html#requirements) (which is currently being expanded to include easyblocks) is to have an ssh key registered on GitHub.

**Comment by kelseymh** [comment]
Thanks for the reply!  I have my SSH keys registered; I got that warning doing a command-line pull request with my SSH key in use.  I brought it here assuming it meant that EasyBuild's CONTRIBUTING.rst needed updating, since the instructions there specifically recommend supplying username and password through curl.

**Comment by ocaisa** [comment]
Whoops, I didn't look at that line very well, sorry. You're right those docs are (now) out of date, and will soon be even more out of date when https://github.com/easybuilders/easybuild-framework/pull/3206 gets merged.

If it was my call I would probably just remove that section since [you can now use things like `Closes #100`](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) so there's no reason to do something overly complicated, I'll open a PR for that.

**Comment by kelseymh** [comment]
Interesting!  It sounds like the EasyBlocks repository will soon have more suppport with `eb` options, the way EasyConfigs does.  Thank you for the replies!
