### ISSUE TITLE
Setting CC to gcc on Cray XC40

### ISSUE THREAD

**Issue by menzzana** [easybuilders/easybuild-easyblocks#2284]
During installation of CrayCCE on an Cray XC40 system.
Looking at the log file I discovered...

```
== 2020-12-16 10:53:57,305 filetools.py:456 INFO Command gcc found at /usr/bin/gcc
== 2020-12-16 10:53:57,305 toolchain.py:274 INFO Found compiler command gcc at /usr/bin/gcc, so setting $CC in minimal build environment
== 2020-12-16 10:53:57,307 filetools.py:456 INFO Command g++ found at /usr/bin/g++
== 2020-12-16 10:53:57,307 toolchain.py:274 INFO Found compiler command g++ at /usr/bin/g++, so setting $CXX in minimal build environment
== 2020-12-16 10:53:57,307 environment.py:97 INFO Environment variable CC set to gcc (previously undefined)
== 2020-12-16 10:53:57,307 environment.py:97 INFO Environment variable CXX set to g++ (previously undefined)
```

As this is a cray system I am using the `PrgEnv-gnu` wrappers, which has a different version of the GNU compiler than `/usr/bin/gcc` so why does it find `/usr/bin/gcc` and then changes the environment variable CC to `gcc`, CXX to `g++` ?
In this case prior of using easybuild I also did...
```
  export CXX=CC
  export CC=cc
  export FC=ftn
module swap PrgEnv-cray PrgEnv-gnu
```

so it should not say it is undefined, and also should use the compiler in the wrapper rather than `/usr/bin/gcc`?

During installation of easybuild configs it says...

```
WARNING: $CC was defined as 'cc', but is now set to 'gcc' in minimal build environment
WARNING: $CXX was defined as 'CC', but is now set to 'g++' in minimal build environment
```

...so why does he not detect the wrapper for the GNU environment?

**Comment by boegel** [comment]
During the installation of the `CrayCCE` toolchain the build environment that is set up by EasyBuild is irrelevant, because nothing is actually being compiled when installing `CrayCCE`...
All that is being done is generating a module file which can then be used as a `toolchain` in EasyBuild (see for example [GSL-2.5-CrayCCE-20.08.eb](https://github.com/eth-cscs/production/blob/master/easybuild/easyconfigs/g/GSL/GSL-2.5-CrayCCE-20.08.eb)).

When a non-system toolchain (for example a version of `CrayCCE`) is used, EasyBuild will set up the build environment very differently, based on the implementation of the components of the toolchain (see the [craycce](https://github.com/easybuilders/easybuild-framework/blob/develop/easybuild/toolchains/craycce.py) toolchain definition, and the support for the [Cray PE compilers](https://github.com/easybuilders/easybuild-framework/blob/develop/easybuild/toolchains/compiler/craype.py)).

The log messages you are seeing are because EasyBuild sets up a "minimal build environment" when it is being told to install something with the "system" toolchain, which is a pretty recent change (see https://github.com/easybuilders/easybuild-framework/pull/3399).
You can control the minimal build environment via the `--minimal-build-env` EasyBuild configuration option; the default value is "`CC:gcc,CXX:g++`", which explains what you're seeing.

But that is only relevant when using the `system` toolchain to install something, not when using a non-system toolchain like `CrayCCE` (then a *full* build environment is set up, not a minimal one).

Do let us know if this clarifies things (and if it does, please close the issue).

**Comment by menzzana** [comment]
Yes, Thank you for the explanation.
