### ISSUE TITLE
Possibility to extend Anaconda3/2021.05 module with additional conda packages

### ISSUE THREAD

**Issue by Mycron** [easybuilders/easybuild-easyblocks#2594]
Hello, guys!
I'm searching the proper way how to extend standard installation of Anaconda3/2021.05 from its easyconfig with some additional conda packages. I found out a separate conda easyblock, but it creates a separate environment for that. https://github.com/easybuilders/easybuild-easyblocks/blob/0dd2c6bc1987ed2cd87ad7e9a1c50607b363cafd/easybuild/easyblocks/generic/conda.py#L75 For my case I want to use Anaconda module installation directory. How to deal with it, is it possible or do I have to create my own custom block to use conda to install additional packages inside Anaconda or something completely different?
Here is what I want to have (its similar to PythonBundle structure):
```

...skipped part of Anaconda easyconfig...
exts_defaultclass = conda
exts_list = [
    ('qgrid', '1.3.1', {
        'checksums': ['...'],
    }),
    ('jupyterlab-git, 'its_version_here', {
        'checksums': ['...'],
    }),
]

...skipped part of Anaconda easyconfig...
```

Now I'm using a workaround for this by coding it as a sanity_check part:
```
sanity_check_commands = [
    "conda install -n base -c conda-forge mamba",
    "conda install -n base -c conda-forge conda-pack",
    "conda install -n base -c conda-forge jupyterlab-git",
    "conda install -n base -c conda-forge qgrid",
]
```

**Comment by branfosj** [comment]
It is deliberate that the Anaconda, or Miniconda, install provides just the base conda environment. This is so that this install acts as a standalone and not tied to any particular packages (or versions of those packages).

If I was looking at adding this, I'd add a `postinstallcmds` section:
```
postinstallcmds = [
    "source %(installdir)s/bin/activate && conda install -n base -c conda-forge mamba",
]
```

You could look to a custom version of the [Anaconda easyblock](https://github.com/easybuilders/easybuild-easyblocks/blob/develop/easybuild/easyblocks/a/anaconda.py) to source the environment and then install the packages as extensions. There is information on [including custom easyblocks](https://docs.easybuild.io/en/latest/Including_additional_Python_modules.html#include-easyblocks).

**Comment by Mycron** [comment]
Thanks, @branfosj ! Your example with **postinstallcmds** looks good for my case.
