### ISSUE TITLE
numpy.py ignores 'ignore_test_result' variable

### ISSUE THREAD

**Issue by surak** [easybuilders/easybuild-easyblocks#2686]
The numpy.py easyblock has a variable to ignore test results https://github.com/easybuilders/easybuild-easyblocks/blob/5630a70d6f9940d822747e7c45d76ee04f4af2f2/easybuild/easyblocks/n/numpy.py#L59

Which is never used:

https://github.com/easybuilders/easybuild-easyblocks/blob/5630a70d6f9940d822747e7c45d76ee04f4af2f2/easybuild/easyblocks/n/numpy.py#L286-L291

**Comment by boegel** [comment]
@surak `ignore_test_result` is used to determine whether any failures of the `numpy` test suite should be ignored or not.

It currently doesn't apply to the matrix dot product test that is also used, basically because you can already use `blas_test_time_limit` to being more forgiving w.r.t. how long that test takes.
