### ISSUE TITLE
Python packages are being installed to local/lib/python*/dist-packages due to tweaks to sysconfig.py in OS (Ubuntu 22.04)

### ISSUE THREAD

**Issue by anselmicz** [easybuilders/easybuild-easyblocks#2976]
**Problem description**

Hi. Recently, one of my machines started experiencing problems with installing EasyBuild via the bootstrap method.

```
== 2022-11-26 22:18:10,235 easyblock.py:3774 INFO Running method sanity_check_step part of step sanitycheck
== 2022-11-26 22:18:10,281 build_log.py:169 ERROR EasyBuild crashed with an error (at easybuild/eb_tmp/local/lib/python3.10/dist-packages/easybuild/base/exceptions.py:124 in __init__): Failed to isolate installed egg dir for easybuild-framework (at easybuild/eb_tmp/local/lib/python3.10/dist-packages/easybuild/easyblocks/e/easybuildmeta.py:235 in sanity_check_step)
```

I use a custom build script I wrote based on the official instructions in the Lua, Lmod and EasyBuild documentations:
https://github.com/anselmicz/easybuild-installer/blob/main/easybuild.sh

My current builds fail during the sanity check phase, I'm enclosing the build log, environment at the time of installation, and trace output as a gist:
https://gist.github.com/anselmicz/72d1a0239cf67b685ed878aef2f61359

The error itself comes from https://github.com/boegel/easybuild-easyblocks/blob/develop/easybuild/easyblocks/e/easybuildmeta.py#L235

In a Slack conversation, @ocaisa mentioned that the error may be somehow connected to
https://github.com/easybuilders/easybuild-easyblocks/pull/2805

**System**

***OS***
Debian bookworm/sid

***Custom dependencies***
```
Lua/5.1.4.9
Lmod/8.5
```

***System packages***
```
python3/3.10.6
python3-pip/22.3
wget/1.21.3
gcc/12.2.0
make/4.3
rsync/3.2.6
tcl-dev/8.6.11
libreadline-dev/8.2
libibverbs-dev/43.0
xdot/1.2
```

***Python packages***
```
setuptools/65.6.3
python-graph-core/1.8.2
python-graph-dot/1.8.2
archspec/0.2.0
autopep8/2.0.0
GitPython/3.1.29
pep8/1.7.1
pycodestyle/2.10.0
Rich/12.6.0
```

Do you have any thoughts on this? I tried lowering both the temporary and to-be-installed versions of EasyBuild, but the issue persists both on `4.6.1` and  `4.6.0`, and I can't try `4.5.4` because then the `setuptools` and `setup.py` problems arise.

**Comment by boegel** [comment]
Did some more digging, found some more info:

* ["sysconfig default scheme change in Python 3.10" (on `debian-python` mailing list)](https://lists.debian.org/debian-python/2022/03/msg00039.html);
* In https://github.com/pypa/pip/issues/10978 it's highlighted that this problem isn't specific to Debian/Ubuntu at all, it also affects Fedora 37 (so soon also RHEL & friends?), or even Fedora 36 (based on [this](https://bugzilla.redhat.com/show_bug.cgi?id=2026979) and [this](https://bugzilla.redhat.com/show_bug.cgi?id=2097183)), but there they didn't even bother to introduce a custom installation scheme like Debian/Ubuntu did with `posix_local` (which is not standard in Python, see https://docs.python.org/3/library/sysconfig.html#installation-paths), they just fiddled with the default `posix_prefix` instead, making it harder to detect;
  * [this](https://src.fedoraproject.org/rpms/python3.10/pull-request/124) seems to suggest the change was rolled back in Fedora though...
* Spack has been dealing with this too, see:
  * https://github.com/spack/spack/issues/37632

**Comment by boegel** [comment]
Updates to the `PythonPackage` easyblock are implemented in #2977 to deal with this, using that EasyBuild installs without problems on Ubuntu 22.04.

**Comment by NicolasMelot** [comment]
@boegel redirected me here about the problem on Ubuntu 22.04. I could not follow easybuild installation guide on [Installing EasyBuild tutorial](https://docs.easybuild.io/installation/#eb_as_module). The procedure fails at step 2 with the error:

```
build failed (first 300 chars): Failed to isolate installed egg dir for easybuild-framework (took 1 min 10 secs)
```
 and no other obvious information. The solution discussed here seem to be used with the flag `--include-easyblocks-from-pr 2977`, as in:

```
eb --include-easyblocks-from-pr 2977 --install-latest-eb-release --prefix /tmp/easybuild
```

and it worked immediately as expected on my system.

**Comment by boegel** [comment]
@akesandgren mentioned that he was hitting some problems when testing #2977, so I'm re-opening this issue to try and figure out what was overlooked (I haven't been able to reproduce this problem):

```
== 2023-08-24 16:23:42,987 pythonpackage.py:285 INFO Subdirectories of /scratch/ebtest4/software/EasyBuild/4.8.0/local: ['lib']
== 2023-08-24 16:23:42,988 build_log.py:171 ERROR EasyBuild crashed with an error (at easybuild/base/exceptions.py:126 in __init__): Failed to install EasyBuild packages: [Errno 22] Invalid argument: '/scratch/ebtest4/software/EasyBuild/4.8.0/lib' (at easybuild/easyblocks/e/easybuildmeta.py:155 in install_step)
```

**Comment by boegel** [comment]
I did a quick debugging session on this with @akesandgren, and it's now clear why he was hitting the `Invalid argument` error, which is triggered by EasyBuild trying to symlink `<prefix>/local/lib` to `<prefix>/lib` while `<prefix>/lib` already exists.

In @akesandgren's Ubuntu 22.04 container, Python 3.10 is installed, but `pip` is *not*.
The `EasyBuildMeta` easyblock automatically enables installing EasyBuild with `pip install --prefix ...` for sufficiently recent versions of EasyBuild, if `pip` is installed (and recent enough). Since that condition is not met, the `EasyBuildMeta` easyblock falls back to using `python setup.py install --prefix ...`.

Apparently whether the active Python naming scheme of the system Python is `posix_prefix` (the default) or `posix_local` (the custom one in Ubuntu 22.04) only matters when installing Python packages with `pip install --prefix ...` (or `python3 -m pip install --prefix ...`), *not* when using `python3 setup.py install --prefix ...`.

The changes in #2977 make `PythonPackage` prepare an empty `<prefix>/local/python*/site-packages` directory, based on the active Python naming scheme being `posix_local`, but the installation is actually done in `<prefix>/local/python*/site-packages` (as it should be!).
`PythonPackage.install_step` then tries to symlink `local/lib` to `lib` after installing the `easybuild-framework` package, which fails because `<prefix>/lib` exists already.
